# 2019-04-30

* Re-created all figures as necessary
* Polished Methods
* Polished Results
* Polished Discussion

# 2019-04-29

* Further polishing of text
* Created Figure 1
* Prepping for LaTeX typesetting

# 2019-04-28

* Final round of comments addressed in part

# 2019-04-26

* Creating remaining figures

# 2019-04-25

* Working on length fix

# 2019-04-24

* Troubleshot the global analysis output

# 2019-04-18

* Unpacking and calculating slopes for global results
* Re-writing Intro
* Fleshing out Discussion

# 2019-04-17

* Expanded tests to 0.5C/dec trend and 99% missing data

# 2019-04-16

* Edited manuscript through to the discussion section
* First pass at global analysis nearly finished

# 2019-04-15

* Global analysis error trapping

# 2019-04-14

* Implemented and ran code for fixes to sub-optimal data
* Wrote global analysis code
* Began running global analysis code

# 2019-04-12

* Finished first pass on answer to Question 2

# 2019-04-11

* Working towards Question 2

# 2019-03-20

* Basic figures for the re-sample workflow complete

# 2019-03-20

* Working on the consolidated workflow script

# 2019-03-19

* Switching from `pkgdown` to `workflowr` for project management/visualisation

# 2019-03-12

* Incorporated first round of edits from AJH
* Began writing new decadal detection chunk

# 2019-03-07

* Incorporated first round of edits from AJS

# 2019-03-06

* Worked out basic event count results for all vignettes
* Final skeleton of paper

# 2019-03-05

* More missing data work
* Worked through basic decadal trend results

# 2019-03-04

* Working through the missing data analyses

# 2019-02-26

* Working through the duration analyses

# 2019-02-25

* More work on the skeleton
* Beginning to flesh out the sections

# 2019-02-17

* Working over the skeleton

# 2019-02-15

* Back to business

# 2019-01-24

* Looking over skeleton of main text
* Python issue was addressed
  * The difference was caused by the default nature of how each language did/did not interpolate missing data
  * The calculations otherwise still remained the same

# 2019-01-23

* Performed a deep dive on the issues around missing data and the quantile thresholds
    * Must look at step-by-step process in Python code to determine the issue

# 2019-01-17

* Checked that R and Python base results still match up after heatwaveR v0.3.6 release
    * The threshold calculations appear to be affected differently by large amounts of missing data

# 2018-10-30

* More editing on the time series length vignette

# 2018-10-25

* Big changes coming through
* Added two new vignettes:
  * `Assessing the effects of long-term trends`
  * `Assessing the effects of variance`
  
# 2018-10-24

* Finished editing the "simply shorter" section of the time series length vignette

# 2018-10-23

* Beginning aggressive editing of text
* Allowing calculation of events for all year ranges from 3 -- 34
  * Not just 10 20, and 30 years
* Removing all `var` results

# 2018-10-14

* Incorporated ECJO's most recent round of comments into the main two vignettes.

# 2018-09-14

* Added comparison to `r_vs_python.Rmd` for how the two languages handle
  missing data to create climatologies and calculate events.
* Completed the `Ice coverage` section in `missing_data.Rmd`

# 2018-09-14

* Finished up new proposed work on `time_series_duration.Rmd`
* Output word document version of `time_series_duration.Rmd` and `missing_data.Rmd`
* Recompiled vignettes

# 2018-09-13

* Finished up initially proposed work on `missing_data.Rmd`
* Rebuilt site to reflect upversion to v0.0.3

# 2018-09-11

* Minor additions

# 2018-09-10

* Further editing to `time_series_duration.Rmd`

# 2018-09-06

* Finished preliminary random missing data results
* Fixed CI issues with short time series vignette

# 2018-09-05

* Further editing to `time_series_duration.Rmd`
* Began writing `missing_data.Rmd`
* Rebuilt site to host changes

# 2018-09-03

* Added AJS and ECJO feedback into `MHWdetection.Rmd`
* Added AJS and ECJO feedback into `time_series_duration.Rmd`

# 2018-06-21

* More in-depths category comparisons made

# 2018-06-16

* Some pre-emptive thoughts about more category comparisons

# 2018-06-13

* Finished up basic comparisons of categories for different clim periods

# 2018-06-12

* Added significance tests for clims of different lengths for both single and re-sampled clims

# 2018-06-07

* More work on duration section

# 2018-06-06

* More work on duration section

# 2018-06-05

* Smoothed out issues preventing site from being built
* Tweaks to benchmarking of the languages

# 2018-06-01

* Second section of duration vignette nearly finished

# 2018-05-31

* Completed the first section of the duration vignette

# 2018-05-30

* Some musings added to the short duration vignette

# 2018-05-29

* Skeleton vignettes for the proposed research created

# 2018-05-25

* Regenerated vignettes to reflect corrections made in `heatwaveR` code
* Regenerated site to reflect fixes in site structure
* Added LaTeX folder 

# 2018-05-24

* Added a `NEWS.md` file to track changes to the package.
* Ported over the relevant vignettes that were cluttering up the `heatwaveR` site
